---

#LVM installation
# - name: lv apache
#   include: apache_lvm.yml
#   when: apache_use_lvm

- name: Install latest Apache version
  apt: name=apache2 update_cache=yes state=latest

- import_tasks: apache_configure.yml
  tags: [installation]

- import_tasks: apache_securise.yml
  tags: [installation]

- name: Ensure Apache2 service is started
  service: name=apache2 state=started enabled=yes
