---
# tasks file for ansible-apache

- import_tasks: apache_install.yml
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [installation]

#- include: apache_rollback.yml
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
#  tags: [rollback]

- import_tasks: apache_testing.yml
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [testing]
